language: node_js
node_js:
  - "stable"
addons:
  apt:
    packages:
      # needed by Cypress, not in Ubuntu 16+ by default
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - node_modules
    #folder with Cypress binary
    - ~/.cache
before_script:
  - npm install -g npm@latest
  - npm install
  - npm install -g expo-cli
script:
  - npm run test:ci
  - npm ci
  - npm test --silent
after-success:
  - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
  - npx expo publish --non-interactive